import os
import json
import google.generativeai as genai
from jinja2 import Environment, FileSystemLoader
from typing import Any, Optional

class GeminiService:
    def __init__(self, api_key: str):
        self.api_key = api_key
        genai.configure(api_key=api_key)
        self.model = genai.GenerativeModel("models/gemini-2.5-pro")
        self.template_env = Environment(loader=FileSystemLoader("app/templates"))

    def generate_shape_content(self, prompt: str, context: str) -> dict:
        """Sinh nội dung về hình học sử dụng Gemini"""
        # Load template và render prompt
        template = self.template_env.get_template("shape_prompt.j2")
        prompt_text = template.render(
            prompt=prompt,
            context=context
        )

        # Gọi Gemini API (bọc lỗi để luôn trả về an toàn)
        try:
            response = self.model.generate_content(prompt_text)
        except Exception as e:
            # Trả về fallback text nếu dịch vụ Gemini lỗi (HTTP 5xx, timeout, quota, ...)
            return {
                "prompt": prompt_text,
                "result": f"Gemini generate_content error: {str(e)}",
                "type_response": "text",
            }

        def _safe_extract_text(resp: Any) -> tuple[str, Optional[Any]]:
            # Try direct accessor
            try:
                return resp.text, getattr(resp, "candidates", None)
            except Exception:
                pass
            # Try from candidates/parts
            try:
                candidates = getattr(resp, "candidates", []) or []
                for cand in candidates:
                    content = getattr(cand, "content", None)
                    if content is None:
                        continue
                    parts = getattr(content, "parts", None)
                    if not parts:
                        continue
                    for part in parts:
                        text = getattr(part, "text", None)
                        if text:
                            return text, candidates
            except Exception:
                pass
            return "", getattr(resp, "candidates", None)

        response_text, candidates = _safe_extract_text(response)
        if not response_text:
            # Provide a friendly fallback message, include finish_reason if present
            finish_reason = None
            try:
                if candidates and len(candidates) > 0:
                    finish_reason = getattr(candidates[0], "finish_reason", None)
            except Exception:
                finish_reason = None
            fallback_msg = "No content generated by model"
            if finish_reason is not None:
                fallback_msg += f" (finish_reason={finish_reason})"
            return {
                "prompt": prompt_text,
                "result": fallback_msg,
                "type_response": "text",
            }
        
        # Remove markdown if present
        if response_text.startswith("```json"):
            response_text = response_text.replace("```json", "").replace("```", "").strip()
        
        try:
            # Parse JSON response
            result = json.loads(response_text)
            return {
                "prompt": prompt_text,
                "result": result.get("content", response_text),
                "type_response": result.get("type", "text"),
            }
        except json.JSONDecodeError:
            # Fallback nếu response không phải JSON
            return {
                "prompt": prompt_text,
                "result": response_text,
                "type_response": "text",
            }
        except Exception:
            # Fallback nếu JSON không có đúng cấu trúc
            return {
                "prompt": prompt_text,
                "result": response_text,
                "type_response": "text",
            }